stages:
  - test
  - Static analysis
  - build
  - deploy

variables:
  SONAR_PROJECTKEY: "$CI_PROJECT_NAME"
  SONAR_HOST_URL: "https://sonarqube.neogeo.fr"
  SONAR_LOGIN: $SONAR_TOKEN
  GIT_DEPTH: 0
  # Used to configure CI Test
  POSTGRES_DB: geocontrib
  POSTGRES_USER: geocontrib
  POSTGRES_PASSWORD: geocontrib
  POSTGRES_HOST_AUTH_METHOD: trust


build testing docker image:
  stage: build
  only:
    - develop
  tags:
    - build_docker
  variables:
    DOCKER_TAG: testing
  script:
    - cat $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
    - cd docker
    - docker-compose build geocontrib
    - docker-compose push geocontrib
    - echo Image docker neogeo/geocontrib:${DOCKER_TAG} livrée

deploy testing docker image:
  stage: deploy
  only:
    - develop
  tags:
    - build
  image:
    name: curlimages/curl
  script:
    - curl -X POST      -F token=$TRIGGER_TOKEN -F ref=main      https://git.neogeo.fr/api/v4/projects/226/trigger/pipeline

build stable docker image:
  stage: build
  only:
    - master
  tags:
    - build_docker
  variables:
    DOCKER_TAG: latest
  script:
    - cat $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
    - cd docker
    - docker-compose build geocontrib
    - docker-compose push geocontrib
    - echo Image docker neogeo/geocontrib:${DOCKER_TAG} livrée

build tagged docker image:
  stage: build
  only:
    - tags
  tags:
    - build_docker
  variables:
    DOCKER_TAG: $CI_COMMIT_TAG
  script:
    # Don't build tag id package.json as wrong version
    - grep "__version__ = '$CI_COMMIT_TAG'" geocontrib/__init__.py
    - cat $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
    - cd docker
    - docker-compose build geocontrib
    - docker-compose push geocontrib
    - echo Image docker neogeo/geocontrib:${DOCKER_TAG} livrée


sonarqube-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  only:
    - develop
  stage: Static analysis
  dependencies:
    - test
  allow_failure: true
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.projectVersion=$CI_COMMIT_BRANCH

test:
  stage: test
  image: python:3.7
  services:
    - redis
    - postgis/postgis
  variables:
    REDIS_HOST: "redis"
    DB_HOST: "postgis-postgis"
  before_script:
    - apt update && apt install -y --no-install-recommends libproj-dev gdal-bin
  script:
    - pip install -r requirements-dev.txt -r requirements.txt
    - django-admin startproject config .
    - cp -r config_sample/* config/
    - ./manage.py check
    - ./manage.py makemigrations --check
    - pytest --junitxml=xunit-reports/xunit-result-pytest.xml --cov-report xml:coverage-reports/coverage-pytest.xml --cov .
  artifacts:
    paths:
    - coverage-reports/
    - xunit-reports/
    expire_in: 1 week

