site_name: Documentation Géocontrib
site_url: https://geocontrib.readthedocs.io
nav:
  - Général:
    - documentation_fonctionnelle/index.md
  - Utilisateurs:
    - documentation_fonctionnelle/users.md
  - Projets:
    - documentation_fonctionnelle/project_settings.md
    - documentation_fonctionnelle/project_template.md
    - documentation_fonctionnelle/moderation.md
    - documentation_fonctionnelle/basemaps.md
    - documentation_fonctionnelle/subscription.md
    - documentation_fonctionnelle/project_sharing.md
  - Types de signalements:
    - documentation_fonctionnelle/custom_fields.md
    - documentation_fonctionnelle/symbology.md
    - documentation_fonctionnelle/import_export.md
    - documentation_fonctionnelle/list_of_saved_values.md
  - Signalements:
    - documentation_fonctionnelle/status.md
    - documentation_fonctionnelle/feature_editing.md
    - documentation_fonctionnelle/featurelink.md
  - Fonctionnalités:
    - documentation_fonctionnelle/offline_mode.md
    - documentation_fonctionnelle/external_access.md
    - documentation_fonctionnelle/browse_through_list_of_features.md
    - documentation_fonctionnelle/flatpages.md
    - documentation_fonctionnelle/geocoder.md
    - documentation_fonctionnelle/geocontrib_IDGO.md

theme: readthedocs
