---
version: "3.5"

services:

  geocontrib:
    container_name: "geocontrib_django"
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - geocontrib/geocontrib-alone.env
    ports:
      - "5000:5000"
    volumes:
      - geocontrib_media:/home/apprunner/geocontrib_app/media
      - geocontrib_static:/home/apprunner/geocontrib_app/static
    depends_on:
      - geocontrib-db

  # ---------------------------------------------------------------- #
  geocontrib-db:
    container_name: "geocontrib_db"
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_USER=geocontrib
      - POSTGRES_PASSWORD=geocontrib
      - POSTGRES_DB=geocontrib
    volumes:
      - geocontrib_data:/var/lib/postgresql/data/

  # ---------------------------------------------------------------- #
  geocontrib-nginx:
    container_name: "geocontrib_nginx"
    build:
      context: nginx
    env_file:
      - geocontrib/geocontrib-alone.env
    volumes:
      - geocontrib_media:/opt/geocontrib/media
      - geocontrib_static:/opt/geocontrib/static
    ports:
      - "8000:80"
    depends_on:
      - geocontrib

volumes:
  geocontrib_data:
  geocontrib_media:
  geocontrib_static:
