---
version: "3.5"

services:

  geocontrib: &geocontrib
    image: neogeo/geocontrib
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - geocontrib/geocontrib-alone.env
    volumes:
      - geocontrib_media:/home/apprunner/geocontrib_app/media
      - geocontrib_static:/home/apprunner/geocontrib_app/static
    depends_on:
      - postgres
      - redis

  celery:
    <<: *geocontrib
    command: src/docker/geocontrib/start_celery.sh

  # ---------------------------------------------------------------- #
  nginx:
    build:
      context: nginx
    env_file:
      - geocontrib/geocontrib-alone.env
    volumes:
      - geocontrib_media:/opt/geocontrib/media
      - geocontrib_static:/opt/geocontrib/static
    ports:
      - "8000:80"
    depends_on:
      - geocontrib

  # ---------------------------------------------------------------- #
  postgres:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_USER=geocontrib
      - POSTGRES_PASSWORD=geocontrib
      - POSTGRES_DB=geocontrib
    volumes:
      - geocontrib_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  geocontrib_data:
  geocontrib_media:
  geocontrib_static:
